### PR TITLE
change license to Apache 2.0

### PR DESCRIPTION
**Pull request by janfb**
In line with the planned license change in [sbi](https://github.com/sbi-dev/sbi/pull/997), I suggest to change the license of pyknos to Apache 2.0 as well. Please see https://github.com/sbi-dev/sbi/pull/997 for details. 

Please indicate your approval of this change by approving this PR or by commenting below. 

Thanks 🙏

### CODE REVIEW

**Review by michaeldeistler — APPROVED** [review]
Thanks Jan, I approve of changing the license of the pyknos repo to Apache 2.0

**Comment by janfb** [comment]
@conormdurkan we need your approval as well because it's all based on your MDN implementation :)

**Comment by janfb** [comment]
@harry-fuyu we kindly ask for your approval because you contributed during your internship with us.

**Comment by harry-fuyu** [comment]
Hi Jan,

Sorry for the late reply, of course I agree with the change. Hope all is
well with you!

Best regards,
Harry

**Comment by janfb** [comment]
Hi Harry,

thanks for your reply!
While you are at it, could you please also approve the change in SBI?
https://github.com/sbi-dev/sbi/pull/997

Thanks,
Jan

**Comment by harry-fuyu** [comment]
Hi Jan,

Done! I didn’t get email notification for the mention, sorry for the delay!

Best regards,
Harry

**Review by jnsbck — APPROVED** [review]

**Comment by michaeldeistler** [comment]
@alvorithm @jan-matthis @conormdurkan please have a look and approve the pull request if you are fine with the change.

**Comment by alvorithm** [comment]
While in general I remain a proponent of strong copyleft licenses, I also wholeheartedly share the goal to make pyknos and sbi approachable for a wider community of users and developers. Acknowledging compelling arguments made by fellow team members, I am now keen to find out in practice to what extent adopting weaker copyleft might help to that end.  

Hence, I approve relicensing pyknos under the Apache 2.0 license.

**Review by jan-matthis — APPROVED** [review]

**Comment by michaeldeistler** [comment]
@conormdurkan could you please have a look and approve the pull request if you are fine with the change.

**Comment by janfb** [comment]
Given that @conormdurkan agreed to the re-licensing of the code in `sbi`, and the code used here is actually the same code, I would opt for merging this pull request soon.

**Comment by michaeldeistler** [comment]
I would be fine with merging too.

**Pull request merged**
